# Generated by Django 3.2.13 on 2022-11-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('trailer', models.CharField(max_length=150, verbose_name='Trailer')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('poster', models.CharField(max_length=100, verbose_name='Poster')),
                ('estado', models.CharField(choices=[('D', 'Disponible'), ('N', 'No disponible')], max_length=1, verbose_name='Estado')),
                ('baja', models.BooleanField(default=0)),
            ],
        ),
    ]
