# Generated by Django 3.2.14 on 2022-12-13 02:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date(2022, 12, 12), verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('trailer', models.CharField(max_length=150, verbose_name='Trailer')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('baja', models.BooleanField(default=0)),
                ('poster', models.ImageField(null=True, upload_to='posters')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='administracion.funcion')),
            ],
        ),
        migrations.AddField(
            model_name='funcion',
            name='pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='peliculas', to='administracion.pelicula'),
        ),
    ]
