# Generated by Django 3.2.14 on 2022-12-15 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='fecha',
            field=models.DateField(default=datetime.date(2022, 12, 14), verbose_name='Fecha'),
        ),
    ]
