# Generated by Django 3.2.14 on 2022-11-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('mail', models.EmailField(max_length=254, verbose_name='Email')),
                ('contraseña', models.CharField(max_length=100, verbose_name='Contraseña')),
            ],
        ),
    ]
