# Generated by Django 3.2.14 on 2022-11-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='baja',
            field=models.BooleanField(default=0),
        ),
    ]
