# Generated by Django 3.2.14 on 2022-12-10 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_baja'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
